# Generated by Django 6.0.1 on 2026-01-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='channel_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
