# Generated by Django 6.0.3 on 2026-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_company_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
