"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'old.kik-soft.ru',
]
CSRF_TRUSTED_ORIGINS = ['https://old.kik-soft.ru']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #"whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'profiles',
    'main_site',
    'communications',
    # 'tg_bot_user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django_bot',
        'USER': 'django_admin',
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),  #'host.docker.internal',  # 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            # Set the connection timeout to 5 seconds
            'connect_timeout': 5,
        }

    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Europe/Moscow'
TIME_FORMAT = 'H:i'
TIME_INPUT_FORMATS = [
    '%H:%M:%S',  # '14:30:59'
    '%H:%M:%S.%f', # '14:30:59.000200'
    '%H:%M',     # '14:30'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

FORCE_SCRIPT_NAME = "" #"/dj"
STATIC_URL = FORCE_SCRIPT_NAME + "/static/"

#STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS = [
#     BASE_DIR / 'staticfiles',
# ]

AUTH_USER_MODEL = 'profiles.Profile'
BOT_TOKEN = os.environ.get("BOT_TOKEN")
BASE_SITE = os.environ.get("BASE_SITE")
ADMIN_TG_ID = int(os.environ.get("ADMIN_TG_ID"))
TG_WEBHOOK = f"{BASE_SITE}/webhook"

ZULIP_API_KEY = os.environ.get('ZULIP_API_KEY')
ZULIP_EMAIL = os.environ.get('ZULIP_EMAIL')
ZULIP_SITE = os.environ.get('ZULIP_SITE')
ZULIP_ALLOW_INSECURE = True
ZULIP_STAFF_IDS = [8,9,11,12,15]
NONAME_CHANNEL_NAME = "Noname"
MAX_FILE_SIZE = 5  # MBytes

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/django.log",
            "maxBytes": 1000000,
            "backupCount":3,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
    },
}



try:
    from conf.local_settings import *
    print(40*"*", "Imported local_settings")
except ImportError as e:
    print(40*"*", "Using only prod settings")
    pass

